version: "4"
services:
    api:
        restart: always
        build: ./
        # volumes:
        #     - namedV: /app:ro
        ports:
            - "5000:5000"

# volumes:
#   namedV:
        
    
    # ui:
    #     image: dhiraj30/workload_profiler_ui:frontend_workload
    #     ports: 
    #         - "3000:3000"